[versions]
kotest = "5.9.1"

[libraries]
kotest-runner = { module ="io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-framework-datatest = { module ="io.kotest:kotest-framework-datatest", version.ref = "kotest" }
guava = { module = "com.google.guava:guava", version = "33.4.0-jre" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.1.21" }
